name:    SVGServer2
version: "0.0.0"

dependencies:
  - base
  - yesod
  - yesod-core
  - yesod-websockets
  - websockets
  - text
  - time
  - conduit
  - hxt
  - optparse-applicative
  - transformers
  - yesod-auth
  - yesod-auth-oauth2
  - http-conduit
  - yesod-form
  - fsnotify
  - containers
  - stm
  - process
  - warp
  - warp-tls
  - entropy
  - bytestring
  - base64-bytestring


# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  svgserver2:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SVGServer2
